### PR TITLE
Sync OCKPatient, OCKCarePlan, OCKContact with KnowledgeVector

### LINKED ISSUE #437: Syncing with KnowledgeVector additions
I made additions to sync OCKPatient, OCKCarePlan, and OCKContact in CareKit on this [branch](https://github.com/cbaker6/CareKit/tree/pod_vector). It's mostly a port of the functionality from syncing Tasks and Outcomes with the exception of OCKContact as a required an extra step to delete during a mergeRevision. For OCKPatient, OCKCarePlan, and OCKContact, I currently do nothing in `confirmUpdateWillNotCauseDataLoss`, but I can image there needs to be something there when a Contact or CarePlan is related to a Patient who has been deleted...

I didn't create a PR on this since the KnowledgeVector part is still in beta, but I did create some additional test cases in [TestStore+BuildRevisions.swift](https://github.com/cbaker6/CareKit/blob/d527a26d9ae5530908184cb8fe84a72c453b7ff2/CareKitStore/CareKitStoreTests/OCKStore/TestStore%2BBuildRevisions.swift#L132), [TestStore+ConsumeRevisions.swift](https://github.com/cbaker6/CareKit/blob/d527a26d9ae5530908184cb8fe84a72c453b7ff2/CareKitStore/CareKitStoreTests/OCKStore/TestStore%2BConsumeRevisions.swift#L411), and [TestStore+Sync.swift](https://github.com/cbaker6/CareKit/blob/5e4580a0b57b8434d4fda9ea23bbb9568d195975/CareKitStore/CareKitStoreTests/OCKStore/TestStore%2BSync.swift#L317) to make sure everything was working, so they may be useful. 

If you think a part of it fits a PR, let me know and I can set it up.

### PR DESCRIPTION
**Pull request by cbaker6**
Adds the ability to synchronize the rest go the entities. ~Also removes the restriction of changing the number of OCKPatient's in the OCKStore after it's created~

Close #437

### CODE REVIEW

File: CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift [hunk 1]
```diff
@@ -60,15 +60,12 @@ extension OCKStore {
                           completion: ((Result<[OCKPatient], OCKStoreError>) -> Void)? = nil) {
         context.perform {
             do {
-                try self.validateNumberOfPatients()
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift:63]: Can we add this line back in? We'd like to tackle removing the 1 patient limit as a separate issue. That probably needs to be paired together with some other considerations, like updating the `OCKDailyTasksPageViewController` to make sure it show the tasks for a 1 specific patient.

File: CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift [hunk 2]
```diff
@@ -134,6 +130,60 @@ extension OCKStore {
...
+    /// The copyUUIDs argument should be true when ingesting tasks from a remote to ensure
+    /// the UUIDs match on all devices, and false when creating a new version of a task locally
+    /// to ensure that the new version has a different UUID than its parent version.
+    ///
+    /// - Parameters:
+    ///   - tasks: The new versions of the tasks.
+    ///   - copyUUIDs: If true, the UUIDs of the tasks will be copied to the new versions
+    func updateCarePlansWithoutCommitting(_ plans: [Plan], copyUUIDs: Bool) throws -> [Plan] {
+        try validateUpdateIdentifiers(plans.map { $0.id })
+        try confirmUpdateWillNotCauseDataLoss(plans: plans)
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift:155]: I think we can remove this for now, since the implementation doesn't actually do anything right now.

File: CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift [hunk 3]
```diff
@@ -134,6 +130,60 @@ extension OCKStore {
...
+        let heads = fetchHeads(OCKCDCarePlan.self, ids: plans.map { $0.id })
+        for plan in heads {
+
+            // For each task, gather all outcomes
+            var currentVersion: OCKCDCarePlan? = plan
+            while let version = currentVersion {
+                currentVersion = version.previous as? OCKCDCarePlan
+            }
+        }
+    }
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift:185]: Let's remove this for the time being as well. The only place where data loss is presently a concern is when updating tasks. I'll put comments on the other entities' methods as well, just to track them.

File: CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift [hunk 4]
```diff
@@ -120,6 +116,60 @@ extension OCKStore {
...
+    /// The copyUUIDs argument should be true when ingesting tasks from a remote to ensure
+    /// the UUIDs match on all devices, and false when creating a new version of a task locally
+    /// to ensure that the new version has a different UUID than its parent version.
+    ///
+    /// - Parameters:
+    ///   - tasks: The new versions of the tasks.
+    ///   - copyUUIDs: If true, the UUIDs of the tasks will be copied to the new versions
+    func updateContactsWithoutCommitting(_ contacts: [Contact], copyUUIDs: Bool) throws -> [Contact] {
+        try validateUpdateIdentifiers(contacts.map { $0.id })
+        try confirmUpdateWillNotCauseDataLoss(contacts: contacts)
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift:142]: See above

File: CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift [hunk 5]
```diff
@@ -120,6 +116,60 @@ extension OCKStore {
...
+        let heads = fetchHeads(OCKCDContact.self, ids: contacts.map { $0.id })
+        for contact in heads {
+
+            // For each task, gather all outcomes
+            var currentVersion: OCKCDContact? = contact
+            while let version = currentVersion {
+                currentVersion = version.previous as? OCKCDContact
+            }
+        }
+    }
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift:172]: See above

File: CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift (hunk 1 above)
Comment (cbaker6) [reply CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift:63]: Not a problem, I added this back and reverted back to original test cases for patient

File: CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift [hunk 6]
```diff
@@ -240,6 +240,11 @@ extension OCKStore {
             let beforePredicate = NSPredicate(format: "%K < %@", #keyPath(OCKCDOutcome.date), interval.end as NSDate)
             predicate = NSCompoundPredicate(andPredicateWithSubpredicates: [predicate, afterPredicate, beforePredicate])
         }
+        
+        if !query.uuids.isEmpty {
+            let versionPredicate = NSPredicate(format: "%K IN %@", #keyPath(OCKCDObject.uuid), query.uuids)
+            predicate = NSCompoundPredicate(andPredicateWithSubpredicates: [predicate, versionPredicate])
+        }
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift:247]: This looks like it might be duplicate code. I see another if statement right below this that also checks if the uuids array is empty.

File: CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift [hunk 7]
```diff
@@ -124,6 +119,61 @@ extension OCKStore {
...
+    /// The copyUUIDs argument should be true when ingesting tasks from a remote to ensure
+    /// the UUIDs match on all devices, and false when creating a new version of a task locally
+    /// to ensure that the new version has a different UUID than its parent version.
+    ///
+    /// - Parameters:
+    ///   - tasks: The new versions of the tasks.
+    ///   - copyUUIDs: If true, the UUIDs of the tasks will be copied to the new versions
+    func updatePatientsWithoutCommitting(_ patients: [Patient], copyUUIDs: Bool) throws -> [Patient] {
+        try validateUpdateIdentifiers(patients.map { $0.id })
+        try confirmUpdateWillNotCauseDataLoss(patients: patients)
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift:146]: See above

File: CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift [hunk 8]
```diff
@@ -124,6 +119,61 @@ extension OCKStore {
...
+        let heads = fetchHeads(OCKCDPatient.self, ids: patients.map { $0.id })
+        for patient in heads {
+
+            // For each task, gather all outcomes
+            var currentVersion: OCKCDPatient? = patient
+            while let version = currentVersion {
+                currentVersion = version.previous as? OCKCDPatient
+            }
+        }
+    }
```
Comment (erik-apple) [inline CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift:176]: See above

File: CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift (hunk 1 above)
Comment (erik-apple) [reply CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift:63]: Thanks! We'll get to removing the patient cap eventually!

File: CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift (hunk 2 above)
Comment (cbaker6) [reply CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift]: Yup, I guess I was doing that as you were writing the comments 🙃

Comment (erik-apple) [reply CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift]: Wow, you're just that good!

File: CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift (hunk 6 above)
Comment (cbaker6) [reply CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift]: Removed

**Comment by cbaker6** [comment]
I think something is weird on travis at certain times of day on the test cases. That same exact test failure randomly popped up on #448 here https://travis-ci.org/github/carekit-apple/CareKit/builds/697074836 and went away after I waited a few hours to run the test again. The tests pass locally...

**Comment by erik-apple** [comment]
> I think something is weird on travis at certain times of day on the test cases.

We've noticed this as well. It seems to be a bug on Travis, as we're unable to reproduce the test failure anywhere else. It typically occurs for jobs posted in the evening, and rerunning tests the next morning usually does the trick.

**Comment by erik-apple** [comment]
Thanks again for the PR, and great work!
